services:
    librinfo.security_bundle.global.voter:
        class:      Librinfo\SecurityBundle\Voters\GlobalVoter
        public:     false
        tags:
            - { name: security.voter }

    librinfo.security_bundle.sonata.voter:
        class:      Librinfo\SecurityBundle\Voters\SonataCustomVoter
        public:     false
        arguments: ['@security.authorization_checker',['ROLE_SUPER_ADMIN'] ]